mysite/enquetes/urls.py
from django.urls import path
from enquetes.views import index,detail,results,vote

app_name = 'enquetes'
urlpatterns = [
    path('',index, name='index'),

    path('<int:questao_id>/', detail, name='detail'),

    path('<int:questao_id>/results/', results, name='results'),

    path('<int:questao_id>/vote/', vote, name= 'vote'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('enquetes/', include('enquetes.urls')),
    path('perfil/', include('perfil.urls')),
    path('simulado/',include('simulado.urls')),
]

mysite/enquetes/models.py
from django.db import models

class Pergunta(models.Model):
    texto = models.CharField(
        max_length=200)

    data = models.DateTimeField('Data de publicação')

    def __str__(self):
        return f"{self.texto} - {self.data}"

class Alternativa(models.Model):
    pergunta = models.ForeignKey(
        Pergunta,on_delete=models.CASCADE) 

    voto = models.IntegerField(default=0)

    texto = models.CharField(
        max_length=200
    )    

    def __str__(self):
        return f"{self.pergunta.texto} - {self.texto}"

mysite/enquetes/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse


from enquetes.models import Pergunta
from enquetes.models import Alternativa

# Create your views here.
def index(request):
    quest_recent = Pergunta.objects.order_by('-data')[:25]
    context = {'quest_recent': quest_recent}
    return render(request, 'enquetes/index.html', context)

def detail(request, questao_id):
    try:
        pergunta = Pergunta.objects.get(pk = questao_id)
    except Pergunta.DoesNotExist:
        raise Http404("Questão não existe")
    return render(request, 'enquetes/details.html', {'pergunta':pergunta})

def results(request, questao_id):
    pergunta = get_object_or_404(Pergunta, pk = questao_id)
    return render(request, 'enquetes/results.html',{'pergunta':pergunta})

def vote(request, questao_id):
    pergunta = get_object_or_404(Pergunta, pk = questao_id)
    try:
        selected_alternativa = pergunta.alternativa_set.get(pk = request.POST['alternativa'])
    except (KeyError, Alternativa.DoesNotExist):
        return render(request, 'enquetes/details.html', {'pergunta':pergunta,'error_message':"Você não selecionou uma opção"})
    else:
        selected_alternativa.voto+=1
        selected_alternativa.save()    
        return HttpResponseRedirect(reverse('enquetes:results',
            args=(questao_id,)))

mysite/enquetes/templates/enquetes/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Votação</title>
</head>
<body>
    <legend><h1>{{ pergunta.texto }}</h1></legend>
    <p>Data: {{pergunta.data}}</p>
    {% if error_message %}
        <p>{{ error_message }}</p>
    {% endif %}
    <form action="{% url 'enquetes:vote' pergunta.id %}" method="POST">
    {% csrf_token %}
    <fieldset>
        {% for alt in pergunta.alternativa_set.all %}
            <input type="radio" name="alternativa" 
                id="alt{{ forloop.counter }}" value="{{ alt.id }}">
            <label for="alt{{ forloop.counter }}">
                {{ alt.texto }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>
    <a href="{% url 'enquetes:index' %}">Página Principal</a>
</body>
</html>

mysite/enquetes/templates/enquetes/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href= "{% static 'enquetes/css/style.css' %}">
    <title>PerguntasFrequentes</title>
</head>

<body>
    {% if quest_recent %}
        <h1>Perguntas Frequentes:</h1>
        <ul>
            {% for pergunta in quest_recent %}
                <!--href="/enquetes/{{pergunta.id}}"-->
                <li><a href="{% url 'enquetes:detail' pergunta.id %}">
                    {{ pergunta.texto}}
                    </a>
                    <a href="{% url 'enquetes:results' pergunta.id %}">
                        (Resultado Parcial)
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Nenhuma questão disponível.</p>
    {% endif %}
</body>
</html>

mysite/enquetes/templates/enquetes/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ pergunta.texto }}</h1>

    <ul>
        {% for alt in pergunta.alternativa_set.all %}
            <li>{{ alt.texto }} --> {{alt.voto}}
                voto{{ alt.voto|pluralize }}
            </li>
        {% endfor %}
    </ul>

    <a href="{% url 'enquetes:detail' pergunta.id %}">Votar novamente.</a>
</body>
</html>