mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('enquetes/', include('enquetes.urls')),
    path('perfil/', include('perfil.urls')),
    path('simulado/',include('simulado.urls')),
]

mysite/simulado/urls.py
from django.urls import path
from . import views

app_name = 'simulado'
urlpatterns = [

    path('', views.Simulados.as_view(),
        name='simulados'),
    path('dashboard/', views.dashboard, 
        name='dashboard'),
    path('simulado/<int:simulado_id>/', views.detalheSimulado, 
        name='detalhe'),
    path('simulado/resposta/<int:simulado_id>/', views.resposta.as_view(), 
        name='resposta'),

    path('cadastrosimulado/', views.CriaSimulado.as_view(), 
        name= 'criasimulado'),
    path('criaquestao/<int:simulado_id>/', views.CriaQuestao.as_view(), 
        name= 'criaquestao'),
    path('cadastrousuario/', views.CadastroUsuario.as_view(), 
        name= 'cadastrousuario'),


    path('login/', views.LoginView.as_view(), 
        name= 'login'),
    path('logout/', views.logoutView, 
        name='logout'),

]

mysite/simulado/models.py
from statistics import mode
from django.db import models
from django.contrib.auth.models import User

class Usuario(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Simulado(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=50)
    pont_total = models.DecimalField(max_digits=6,decimal_places=2)
    data_criacao = models.DateField(auto_now_add=True)
    data_fim = models.DateField('Data de encerramento', null=True)
    qtd_questoes = models.IntegerField()

    def __str__(self):
        return f"Titulo: {self.titulo} - Pontuacao: {self.pont_total} "

class Questao(models.Model):
    simulado = models.ForeignKey(Simulado,on_delete=models.CASCADE)
    texto = models.CharField(max_length= 200)
    pontuacao = models.DecimalField(max_digits=6,decimal_places=2, null= True)

    def __str__(self):
        return f"Texto: {self.texto} - Pontuacao: {self.pontuacao} "

class Resposta(models.Model):
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    texto = models.CharField(max_length=200)
    correta = models.BooleanField(default=False)

    def __str__(self):
        return f"Texto: {self.texto}"

mysite/simulado/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import login, logout,authenticate
from .models import Simulado, Questao, Resposta, Usuario


#visualização de simulados específicos, com a opção de submeter;
#visualização do resultado da resposta de um simulado, apresentando as respostas corretas, respostas erradas e a soma das pontuações.

class Simulados(View):
    def get(self, request):
        simulados = Simulado.objects.all()
        contexto = {'simulados':simulados}
        return render(request, 'simulado/simulados.html',contexto)

@login_required(login_url="/simulado/login/")
def dashboard(request):
    meus_simulados = Simulado.objects.filter(usuario = request.user)
    return render(request, 'simulado/dashboard.html',{'simulados': meus_simulados})

def detalheSimulado(request, simulado_id):
    simulado = get_object_or_404(Simulado, pk=simulado_id)
    questoes = Questao.objects.filter(simulado = simulado)

    return render(request, 'simulado/detalheSimulado.html', {'simulado': simulado, 'questoes': questoes})


class resposta(View):
    def post(self, request, simulado_id):
        simulado = get_object_or_404(Simulado, pk=simulado_id)
        questoes = Questao.objects.filter(simulado= simulado)
        lista_respostas = []
        nota = 0
        for q in questoes:
            alternativa = r"alternativa%s"%q.id
            id_alt = request.POST.get(alternativa)
            resposta = get_object_or_404(Resposta, pk= id_alt)
            if resposta.correta:
                nota+= q.pontuacao  
            lista_respostas.append(resposta)
        
        return render(request, 'simulado/respostaSimulado.html', {'simulado': simulado,'respostas': lista_respostas, 'nota': nota})

@method_decorator(login_required(login_url="/simulado/login/"), name='dispatch')
class CriaSimulado(View):
    def get(self, request):
        return render(request, 'simulado/cadastroSimulado.html')

    def post(self, request):
        titulo = request.POST['titulo']
        pontuacao = request.POST.get('pontuacao')
        data_fim = request.POST['data_fim']
        texto_quest = request.POST['texto_quest']
        alt01 = request.POST['alt01']
        alt02 = request.POST['alt02']

        if titulo and pontuacao and texto_quest and alt01 and alt02:
            simulado = Simulado.objects.create(usuario= request.user, titulo= titulo, pont_total= pontuacao, data_fim = data_fim, qtd_questoes = 0)
            questao = Questao.objects.create(texto= texto_quest, simulado= simulado)
            correta = request.POST['correta']
            
            resposta = Resposta.objects.create(texto = alt01, questao = questao)
            if correta == 'alt01':
                resposta.correta = True
                resposta.save()

            resposta = Resposta.objects.create(texto = alt02, questao = questao)
            if correta == 'alt02':
                resposta.correta = True
                resposta.save()

            if request.POST['alt03']:
                resposta = Resposta.objects.create(texto = request.POST['alt03'], questao = questao)
                if correta == 'alt03':
                    resposta.correta = True
                    resposta.save()

            if request.POST['alt04']:
                resposta = Resposta.objects.create(texto = request.POST['alt04'], questao = questao)
                if correta == 'alt04':
                    resposta.correta = True
                    resposta.save()
            simulado.qtd_questoes +=1
            simulado.save()
            pont_simulado = simulado.pont_total
            qtd_quest = simulado.qtd_questoes
            pont_quest = int(pont_simulado)/qtd_quest
            questoes = Questao.objects.filter(simulado = simulado)
            for quest in questoes:
                quest.pontuacao = pont_quest
                quest.save()
        
        return HttpResponseRedirect(reverse('simulado:dashboard'))

@method_decorator(login_required(login_url="/simulado/login/"), name='dispatch')
class CriaQuestao(View):
    def get(self, request, simulado_id):
        simulado = get_object_or_404(Simulado, pk=simulado_id)
        return render(request, 'simulado/cadastroQuestao.html', {'simulado': simulado})
    def post(self, request, simulado_id):
        texto_quest = request.POST['texto_quest']
        alt01 = request.POST['alt01']
        alt02 = request.POST['alt02']

        if texto_quest and alt01 and alt02:
            simulado = get_object_or_404(Simulado, pk = simulado_id)
            questao = Questao.objects.create(texto= texto_quest, simulado= simulado) 
            correta = request.POST['correta']
            
            resposta = Resposta.objects.create(texto = alt01, questao = questao)
            if correta == 'alt01':
                resposta.correta = True
                resposta.save()

            resposta = Resposta.objects.create(texto = alt02, questao = questao)
            if correta == 'alt02':
                resposta.correta = True
                resposta.save()

            if request.POST['alt03']:
                resposta = Resposta.objects.create(texto = request.POST['alt03'], questao = questao)
                if correta == 'alt03':
                    resposta.correta = True
                    resposta.save()

            if request.POST['alt04']:
                resposta = Resposta.objects.create(texto = request.POST['alt04'], questao = questao)
                if correta == 'alt04':
                    resposta.correta = True
                    resposta.save()
            # divide a pontuação de acordo com a qtd de questões no simulado.
            simulado.qtd_questoes +=1
            simulado.save()
            pont_simulado = simulado.pont_total
            qtd_quest = simulado.qtd_questoes
            pont_quest = int(pont_simulado)/qtd_quest
            questoes = Questao.objects.filter(simulado = simulado)
            for quest in questoes:
                quest.pontuacao = pont_quest
                quest.save()

        return HttpResponseRedirect(reverse( 'simulado:detalhe', args=(simulado_id,)))


class CadastroUsuario(View):
    def get(self, request):
        return render(request, 'simulado/cadastroUsuario.html')
    def post(self, request):
        nome = request.POST['nome']
        email = request.POST['email']
        senha = request.POST['senha']
        if nome and email and senha:
            user = User.objects.create_user(
                username=nome, password=senha, email=email)
            Usuario.objects.create(user=user)
            return HttpResponseRedirect(reverse('simulado:login'))
        else:
            erro = 'Informe corretamente os parâmetros necessários!'

            return render(request, 'simulado/cadastroUsuario.html', {'erro': erro})

class LoginView(View):
    def get(self, request):
        return render(request, 'simulado/login.html')
    def post(self, request):
        username = request.POST.get('username')
        senha =  request.POST.get('senha')
        user = authenticate(username = username, password = senha)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('simulado:dashboard'))
        else:
            erro = 'usuario e senha inválidas!'
            return HttpResponseRedirect(reverse('simulado:login'), {'erro': erro})

def logoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse('simulado:simulados'))

mysite/simulado/templates/simulado/cadastroQuestao.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro Questão</title>
</head>
<body>
    <h1>Cadastro Questão</h1>
    <h2>{{ simulado.titulo }}</h2>
    <form action="{% url 'simulado:criaquestao' simulado.id %}" method="POST">
        {% csrf_token %}
            <fieldset>
                <input name="texto_quest" id="" placeholder="Texto da questão" required >
            </fieldset>
        
            <fieldset>
                <input name="alt01" id="" placeholder="alternativa 01" required >
                <input type="radio" name="correta" value="alt01" >Correta
            </fieldset>

            <fieldset>
                <input name="alt02" id="" placeholder="alternativa 02" required >
                <input type="radio" name="correta" value="alt02" >Correta
            </fieldset>

            <fieldset>
                <input name="alt03" id="" placeholder="alternativa 03">
                <input type="radio" name="correta" value="alt03" >Correta
            </fieldset>

            <fieldset>
                <input name="alt04" id="" placeholder="alternativa 04">
                <input type="radio" name="correta" value="alt04" >Correta
            </fieldset>

        <button type="submit" id="form-submit" class="button">Cria questão</button>
    </form>
</body>
</html>

mysite/simulado/templates/simulado/cadastroSimulado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CadastroSimulado</title>
</head>
<body>
    <h1>Cadastro Simulado</h1>
    <form action="{% url 'simulado:criasimulado' %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <input name="titulo" id="" placeholder="Titulo simulado">
        </fieldset>
        <fieldset>
            <input name="pontuacao" type="number" id="" placeholder="Pontuacao simulado" required >
        </fieldset>
        <fieldset>
            Data de encerramento:<input name="data_fim" id="" type="date" placeholder="Data fim" required >
        </fieldset>
        
        <fieldset>
            <input name="texto_quest" id="" placeholder="Texto da questão" required >
        </fieldset>
        <fieldset>
            <input name="alt01" id="" placeholder="alternativa 01" required >
            <input type="radio" name="correta" value="alt01" >Correta
        </fieldset>
        <fieldset>
            <input name="alt02" id="" placeholder="alternativa 02" required >
            <input type="radio" name="correta" value="alt02" >Correta
        </fieldset>
        <fieldset>
            <input name="alt03" id="" placeholder="alternativa 03">
            <input type="radio" name="correta" value="alt03" >Correta
        </fieldset>
        <fieldset>
            <input name="alt04" id="" placeholder="alternativa 04">
            <input type="radio" name="correta" value="alt04" >Correta
        </fieldset>

        <button type="submit" id="form-submit" class="button">Cria simulado</button>
    </form>
</body>
</html>

mysite/simulado/templates/simulado/cadastroUsuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CadastroUsuario</title>
</head>
{% if erro %}
    {{ erro }}
{% endif %}
<body>
    <h1>CADASTRO</h1>
    <form action="{% url 'simulado:cadastrousuario' %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <input name="nome" id="" placeholder="Nome">
        </fieldset>
        <fieldset>
            <input name="email" id="" placeholder="Email" required >
        </fieldset>
        <fieldset>
            <input name="senha" id="" type="password" placeholder="Senha" required >
        </fieldset>
        <button type="submit" id="form-submit" class="button">Cadastrar</button>
    </form>
</body>
</html>

mysite/simulado/templates/simulado/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
    <h1>MEUS SIMULADOS</h1>
    {% for s in simulados %}
    <li>
        <a href="{% url 'simulado:detalhe' s.id %}">
            {{ s.titulo }}
        </a>
    </li>
    {% endfor %}
    <div>
        <a href="{% url 'simulado:criasimulado' %}">Novo simulado</a>
    </div>
    <a href="{% url 'simulado:simulados' %}">Simulados</a>
    <a href="{% url 'simulado:logout' %}">Logout</a>
</body>
</html>

mysite/simulado/templates/simulado/detalheSimulado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhe</title>
</head>
<body>
    <p>Logado como: {{ request.user.username }}</p>
    <h1>SIMULADO: {{ simulado.titulo }}</h1>
    <div>
        <p>Feito por: {{ simulado.usuario }}</p>
        <p>Data criação: {{ simulado.data_criacao }}</p>
        <p>Finaliza em: {{ simulado.data_fim }}</p>
    </div>

    <div>
        <p>Pontuação máxima: {{ simulado.pont_total }}</p>
    </div>
    <ul>
        <form action="{% url 'simulado:resposta' simulado.id %}" method="POST">
            {% csrf_token %}
            {% for questao in questoes %}
                <fieldset>
                    {{ questao }}
                    {% for alt in questao.resposta_set.all %}
                        <div>
                            <input type="radio" name="alternativa{{ questao.id }}" value="{{ alt.id }}">{{ alt.texto }}
                        </div>   
                    {% endfor %}
                </fieldset>
            {% endfor %}
        <input type="submit">
        </form>

        {% if simulado.usuario == request.user %}
            <a href="{% url 'simulado:criaquestao' simulado.id %}">Deseja adicionar mais uma questão?</a>
        {% endif %}
    </ul>
    <a href="{% url 'simulado:simulados' %}">Simulados</a>
</body>
</html>

mysite/simulado/templates/simulado/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h1>LOGIN</h1>
    <p>Logado como: {{ request.user.username }}</p>
    <form action="{% url 'simulado:login' %}" method="POST">
        {% csrf_token %}
        <fieldset>
        <input name="username" id="username" placeholder="Digite seu nome" required >
        </fieldset>
        <fieldset>
        <input name="senha" type="password" id="senha" placeholder="Digite sua senha" required>
        </fieldset>
        <button type="submit" id="form-submit" class="button">Entrar</button>
    </form>
        <p >Não tem uma conta? <a href="{% url 'simulado:cadastrousuario' %}">Cadastrar-se</a></p>
</body>
</html>

mysite/simulado/templates/simulado/respostaSimulado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhe</title>
</head>
<body>
    <h1>RESPOSTAS</h1>
    <p>Logado como: {{ request.user.username }}</p>
    <h1>SIMULADO: {{ simulado.titulo }}</h1>
    <div>
        <p>Feito por: {{ simulado.usuario }}</p>
        <p>Data criação: {{ simulado.data_criacao }}</p>
        <p>Finaliza em: {{ simulado.data_fim }}</p>
    </div>

    <div>
        <p>Pontuação máxima: {{ simulado.pont_total }}</p>
    </div>
    <div>
        <h2>Você tirou: {{ nota }}</h2>
    </div>
    <ul>
        {% for r in respostas %}
            <fieldset>    
                {% if r.correta %}
                    <p style="color: rgb(23, 150, 23);">{{ r.questao }} CORRETA</p>
                {% else %}
                    <p style="color: red;">{{ r.questao }} ERRADA</p>
                {% endif %}
                
                {% for alt in r.questao.resposta_set.all %}
                    {% if r == alt %}
                        {% if r.correta %}
                            <div style="background-color: rgba(62, 204, 62, 0.751);">
                                <input type="radio" name="alternativa{{ alt.questao.id }}" checked>{{ alt.texto }}
                            </div>
                        {% else %}
                            <div >
                                <input type="radio" name="alternativa{{ alt.questao.id }}" checked>{{ alt.texto }}
                            </div>
                        {% endif %}
                    {% else %}
                        {% if alt.correta %}
                            <div style="background-color: rgba(62, 204, 62, 0.751);">
                                <input type="radio" name="alternativa{{ alt.questao.id }}" >{{ alt.texto }}
                            </div>
                        {% else %}
                            <div>
                                <input type="radio" name="alternativa{{ alt.questao.id }}">{{ alt.texto }}
                            </div>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </fieldset>
        {% endfor %}
    </ul>

    <a href="{% url 'simulado:simulados' %}">Simulados</a>
</body>
</html>

mysite/simulado/templates/simulado/simulados.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
    <title>Simulados</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-secondary">
        <div class="container-fluid px-5">
            <a class="navbar-brand" href="{% url 'simulado:simulados' %}">Simulados</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        {% if request.get_full_path == '/' %}
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        {% else %}
                            <a class="nav-link" aria-current="page" href="#">Home</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'simulado:dashboard' %}" class="nav-link active">Meus Simulados</a>
                    </li>
                </ul>
            </div>
        </div>
        {% if request.user.usuario %}
        <div class="navbar-nav ms-auto px-5 mr-5">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle d-inline-block" href="#" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    {{ request.user.username }}
                </a>
                <ul class="dropdown-menu ms-auto">
                    <li><a class="dropdown-item" href="{% url 'simulado:logout' %}">Deslogar</a></li>
                </ul>
            </li>
        </div>


        {% else %}
        <div class="navbar-nav ms-auto px-5 mr-5">
                
                <a href="{% url 'simulado:login' %}" class="btn btn-primary">Login</a>
                <a href="{% url 'simulado:cadastrousuario' %}" class="btn btn-primary">Cadastrar-se</a>
        </div>

        {% endif %}
        </div>

    </nav>

    <ul>
        {% for simulado in simulados %}
        <li>
            <a href="{% url 'simulado:detalhe' simulado.id %}">
                {{ simulado.titulo }}
            </a>
        </li>
        {% empty %}
            <p>Nenhum simulado cadastrado no momento.</p>
        {% endfor %}
    </ul>
</body>

</html>